output "vpc_id"                   { value = aws_vpc.main.id }
output "public_subnet_ids"        { value = [for s in aws_subnet.public : s.id] }
output "private_subnet_ids"       { value = [for s in aws_subnet.private : s.id] }
output "alb_dns_name"             { value = aws_lb.main.dns_name }
output "alb_arn"                  { value = aws_lb.main.arn }
output "target_group_arn"         { value = aws_lb_target_group.control.arn }
output "sg_control_plane_id"      { value = aws_security_group.control_plane.id }
output "sg_event_worker_id"       { value = aws_security_group.event_worker.id }
output "sg_rds_id"                { value = aws_security_group.rds.id }
output "sg_efs_id"                { value = aws_security_group.efs.id }
